name: Publishing

on:
    push:
        tags:
            - "v*"

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y libasound2-dev
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
            - run: cargo test

    build:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
                include:
                    - os: macos-latest
                      bin: rs-player
                    - os: ubuntu-latest
                      bin: rs-player
                    - os: windows-latest
                      bin: rs-player.exe

        needs: test
        name: Publishing for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        steps:
            - name: Installing needed Ubuntu dependencies
              if: matrix.os == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libasound2-dev
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
            - run: cargo build --release
            - uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.os }}
                  path: target/release/${{ matrix.bin }}

    Publish:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/create-release@v1
              id: create_release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: ${{ github.ref }}
                  draft: false
                  prerelease: false

            - uses: actions/download-artifact@v2
              with:
                  path: ./artifact

            - uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./artifact/macos-latest/rs-player
                  asset_name: rs-player-mac
                  asset_content_type: application/zip
            - uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./artifact/ubuntu-latest/rs-player
                  asset_name: rs-player-linux
                  asset_content_type: application/zip
            - uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./artifact/windows-latest/rs-player.exe
                  asset_name: rs-player-win.exe
                  asset_content_type: application/zip
