on:
    push:
        tags:
            - "v*"

jobs:
    publish:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
                include:
                    - os: macos-latest
                      bin: rs-player
                      prefix: macos
                    - os: ubuntu-latest
                      bin: rs-player
                      prefix: linux
                    - os: windows-latest
                      bin: rs-player.exe
                      prefix: win.exe

        name: Publishing for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        steps:
            - name: Installing needed Ubuntu dependencies
              if: matrix.os == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libasound2-dev
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
            - run: cargo build --release
            - uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: target/release/${{ matrix.bin }}
                  asset_name: rs-player-${{ matrix.prefix }}
                  asset_content_type: application/zip
