name: Test

on:
    push:
        branches:
            - master

jobs:
    test:
        name: Test on Ubuntu
        runs-on: ubuntu-latest

        steps:
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y libasound2-dev
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
            - run: cargo test
